#!/bin/sh

el_size=74
from="$1"
to="$2"
el_from=$(printf "$from" | tail -c $el_size)
el_to=$(printf "$to" | tail -c $el_size)
if [ "$el_from" != "$from" ]; then
	el_from="...${el_from}"
fi
if [ "$el_to" != "$to" ]; then
	el_to="...${el_to}"
fi

bold=$(tput bold)
sgr=$(tput sgr0)

printf "${bold}COPY:${sgr} %s ${bold}->${sgr} %s\n" "$el_from" "$el_to"
cp -r "$from" "$to"
